[package]
name = "gcidr"
version = "0.1.0"
authors = ["kolu <nikolay.kalchev@abv.bg>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
